# Sleep after one hour (1*60*60*1000ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
CONFIG_ZMK_SLEEP=y

# Nice!view gem custom status screen
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Disable animation on peripheral (right side) to save battery
CONFIG_NICE_VIEW_GEM_ANIMATION=n

# Bluetooth range boost
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Debounce tuning
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=8
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=8

# NKRO
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# Soft off support
CONFIG_ZMK_PM_SOFT_OFF=y

# ZMK Studio for realtime keymap updates
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
